require 'pathname'
source "https://github.com/CocoaPods/Specs"

use_frameworks!

target 'QCloudCOSXMLDemo' do
pod 'QCloudCOSXML','6.3.9'
pod 'QCloudCore','6.3.9'
pod 'QCloudTrack','6.3.9'
target 'QCloudCOSXMLDemoTests' do
  inherit! :search_paths
end
end

