require 'pathname'
source "https://github.com/CocoaPods/Specs"

use_frameworks!

target 'QCloudCOSXMLDemo' do
pod 'QCloudCOSXML'
pod 'QCloudCore'
pod 'QCloudTrack'
pod 'QCloudCore/DNSLoader' 
target 'QCloudCOSXMLDemoTests' do
  inherit! :search_paths
end
end

