osx_image: xcode11.6
language: objective-c
cache: cocoapods 
podfile: QCloudCOSXMLDemo/Podfile 
xcode_workspace: QCloudCOSXMLDemo.xcworkspace
xcode_scheme: QCloudCOSXMLDemo
xcode_destination: platform=iOS Simulator,OS=13.6,name=iPhone X

before_install:
  - pod repo update
  - pwd
  - cd QCloudCOSXMLDemo

intall:
  - pod install
  
before_script:
 # Create and start emulator
 
  - pwd
  - echo -e "{\"secretID\":\"${secretID}\", \"secretKey\":\"${secretKey}\"}" >> key.json 

notifications:
  email:
    recipients:

      - wjielai@tencent.com
      - fysntian@tencent.com

