require 'pathname'
source  "https://github.com/CocoaPods/Specs"
use_frameworks!


target 'QCloudCOSXMLSwfitDemo' do
  pod 'QCloudCOSXML'
  target 'QCloudCOSXMLSwfitDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
