# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
require 'pathname'
source  "https://github.com/CocoaPods/Specs"
use_frameworks!
install! 'cocoapods', generate_multiple_pod_projects: true
def libpod(name)
 pod name ,path:"../../Libs/#{name}"

end

def bizpod(name)
 pod name ,path:"../../BisnessComponents/COSXML/#{name}"

end

target 'QCloudCOSXMLSwfitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#
 libpod 'QCloudCore'
 bizpod 'QCloudCOSXML'

  target 'QCloudCOSXMLSwfitDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
