# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
require 'pathname'
#source  "https://github.com/CocoaPods/Specs"
use_frameworks!

target 'QCloudCOSXMLSwfitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'QCloudCOSXML'

  target 'QCloudCOSXMLSwfitDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end